/*Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.*/

drop table if exists user_info;
create table if not exists user_info
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) DEFAULT NULL,
    age         INT         DEFAULT NULL,
    email       VARCHAR(255) DEFAULT NULL,
    gmt_deleted DATETIME    DEFAULT '2001-01-01 00:00:00',
    PRIMARY KEY (id)
);

drop table if exists user_role;
create table if not exists user_role
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT      DEFAULT NULL,
    role_id VARCHAR(30) DEFAULT NULL,
    PRIMARY KEY (id)
);


drop table if exists role_info;
create table if not exists role_info
(
    id        VARCHAR(30) NOT NULL,
    role_name VARCHAR(30) DEFAULT NULL,
    PRIMARY KEY (id)
);

drop table if exists product_info;
create table if not exists product_info
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name VARCHAR(255) DEFAULT NULL,
    product_price FLOAT DEFAULT NULL,
    tenant_id   VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
    );

drop table if exists product_category;
create table if not exists product_category
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT DEFAULT NULL,
    category_id BIGINT DEFAULT NULL,
    tenant_id VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
    );
